export enum PerformerType {
    VENDOR = "VENDOR",
    INTERNAL = "INTERNAL"
}

export enum TaskStatus {
    PENDING = "PENDING",
    DOING = "DOING",
    AWAITING_ACCEPTANCE = "AWAITING_ACCEPTANCE",
    INTERNAL_COMPLETED = "INTERNAL_COMPLETED",
    COMPLETED = "COMPLETED",
    ACCEPTED = "ACCEPTED",
    AWAITING_REVIEW = "AWAITING_REVIEW",
    REJECTED = "REJECTED",
    REJECTED_BILLABLE = "REJECTED_BILLABLE",
    REJECTED_SUPPORT = "REJECTED_SUPPORT",
    OVERDUE = "OVERDUE",
    AWAITING_PRICING = "AWAITING_PRICING",
    AWAITING_SUPPORT = "AWAITING_SUPPORT",
    REWORKING = "REWORKING",
    SUPPORT_PENDING = "SUPPORT_PENDING",
    SUPPORT_AWAITING_RETURN = "SUPPORT_AWAITING_RETURN"
}

export enum PricingStatus {
    PENDING = "PENDING",
    BILLABLE = "BILLABLE",
    NON_BILLABLE = "NON_BILLABLE"
}

export enum ViolationType {
    LATE_SUBMISSION = "LATE_SUBMISSION",
    LATE_UNFINISHED = "LATE_UNFINISHED",
    EXCESSIVE_REWORK = "EXCESSIVE_REWORK"
}
