import { Entity, Column, ManyToOne, JoinColumn } from "typeorm";
import { BaseEntity } from "../../../shared/entities/BaseEntity";
import { Projects } from "../../project/entities/Project.entity";
import { Tasks } from "../../task/entities/Task.entity";
import { Users } from "../../user/entities/User.entity";
import { Vendors } from "../../vendor/entities/Vendor.entity";

// Yêu cầu thuê vendor KHÔNG phải một loại riêng: nó là PROJECT (gắn dự án + công việc) nhưng có
// vendorId và isAutoGenerated = true, do hệ thống tự tạo khi giao task cho vendor.
export enum PaymentRequestType {
    PROJECT = "PROJECT",
    OTHER_WORK = "OTHER_WORK"
}

export enum PaymentRequestApprovalStatus {
    DRAFT = "DRAFT",
    PENDING_REVIEWER = "PENDING_REVIEWER",
    NEED_MORE_DOCS = "NEED_MORE_DOCS",
    PENDING_BOD = "PENDING_BOD",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    CANCELLED = "CANCELLED"
}

export enum PaymentDueStatus {
    WAITING = "WAITING",
    DUE_SOON = "DUE_SOON",
    OVERDUE = "OVERDUE",
    PAID = "PAID",
    NOT_APPLICABLE = "NOT_APPLICABLE"
}

export enum PaymentMethod {
    BANK_TRANSFER = "BANK_TRANSFER",
    CASH = "CASH"
}

export interface PaymentRequestFile {
    name: string;
    url: string;
    type?: string;
    size?: number;
    round?: number;
    uploadedAt?: string;
}

// Một dòng lịch sử của yêu cầu thanh toán: tạo mới, bổ sung, duyệt, BOD quyết định, chi tiền...
// Mỗi lần requester "bổ sung" theo yêu cầu NEED_MORE_DOCS, snapshot nội dung/số tiền/hạn/hoá đơn
// TRƯỚC khi bị ghi đè sẽ được lưu lại ở đây để không mất lịch sử.
export interface PaymentRequestHistoryEntry {
    action: "CREATED" | "SUBMITTED" | "SUPPLEMENTED" | "REVIEWED" | "BOD_DECISION" | "PAID" | "CANCELLED";
    at: string;
    byId: string;
    byName?: string | null;
    note?: string | null;
    snapshot?: {
        content: string;
        amount: number;
        dueDate: string | Date;
        invoiceImages: PaymentRequestFile[];
        invoicePdfs: PaymentRequestFile[];
    };
}

@Entity()
export class PaymentRequests extends BaseEntity {

    @Column({
        type: "enum",
        enum: PaymentRequestType
    })
    type: PaymentRequestType;

    @Column({ type: "text" })
    content: string;

    @Column({ type: "decimal", precision: 15, scale: 3 })
    amount: number;

    @Column({ type: "date" })
    dueDate: Date;

    @Column({ type: "date", nullable: true })
    confirmedDueDate: Date | null;

    @Column({ type: "varchar", length: 26, nullable: true })
    confirmedDueDateById: string | null;

    @ManyToOne(() => Users, { nullable: true })
    @JoinColumn({ name: "confirmedDueDateById" })
    confirmedDueDateBy: Users | null;

    @Column({ type: "varchar", length: 26, nullable: true })
    projectId: string | null;

    @ManyToOne(() => Projects, { nullable: true })
    @JoinColumn({ name: "projectId" })
    project: Projects | null;

    @Column({ type: "varchar", length: 26, nullable: true })
    taskId: string | null;

    @ManyToOne(() => Tasks, { nullable: true })
    @JoinColumn({ name: "taskId" })
    task: Tasks | null;

    // Vendor thực hiện công việc (chỉ có giá trị với type = PROJECT khi task được giao cho vendor)
    @Column({ type: "varchar", length: 26, nullable: true })
    vendorId: string | null;

    @ManyToOne(() => Vendors, { nullable: true })
    @JoinColumn({ name: "vendorId" })
    vendor: Vendors | null;

    // true nếu do hệ thống tự tạo (VD: khi phân công task cho vendor), false nếu người dùng tự tạo
    @Column({ type: "boolean", default: false })
    isAutoGenerated: boolean;

    @Column({ type: "jsonb", default: [] })
    history: PaymentRequestHistoryEntry[];

    @Column({ type: "decimal", precision: 15, scale: 3, nullable: true })
    costPrice: number | null;

    @Column({ type: "jsonb", default: [] })
    invoiceImages: PaymentRequestFile[];

    @Column({ type: "jsonb", default: [] })
    invoicePdfs: PaymentRequestFile[];

    @Column({ type: "varchar", length: 26 })
    requesterId: string;

    @ManyToOne(() => Users)
    @JoinColumn({ name: "requesterId" })
    requester: Users;

    @Column({
        type: "enum",
        enum: PaymentRequestApprovalStatus,
        default: PaymentRequestApprovalStatus.DRAFT
    })
    approvalStatus: PaymentRequestApprovalStatus;

    @Column({ type: "varchar", length: 26, nullable: true })
    reviewerId: string | null;

    @ManyToOne(() => Users, { nullable: true })
    @JoinColumn({ name: "reviewerId" })
    reviewer: Users | null;

    @Column({ type: "timestamptz", nullable: true })
    reviewedAt: Date | null;

    @Column({ type: "text", nullable: true })
    reviewNote: string | null;

    @Column({ type: "varchar", length: 26, nullable: true })
    submittedToBodById: string | null;

    @ManyToOne(() => Users, { nullable: true })
    @JoinColumn({ name: "submittedToBodById" })
    submittedToBodBy: Users | null;

    @Column({ type: "timestamptz", nullable: true })
    submittedToBodAt: Date | null;

    @Column({ type: "varchar", length: 26, nullable: true })
    bodDecisionById: string | null;

    @ManyToOne(() => Users, { nullable: true })
    @JoinColumn({ name: "bodDecisionById" })
    bodDecisionBy: Users | null;

    @Column({ type: "timestamptz", nullable: true })
    bodDecisionAt: Date | null;

    @Column({ type: "text", nullable: true })
    bodDecisionReason: string | null;

    @Column({
        type: "enum",
        enum: PaymentDueStatus,
        default: PaymentDueStatus.WAITING
    })
    paymentStatus: PaymentDueStatus;

    @Column({
        type: "enum",
        enum: PaymentMethod,
        nullable: true
    })
    paymentMethod: PaymentMethod | null;

    @Column({ type: "text", nullable: true })
    bankPaymentOrderUrl: string | null;

    @Column({ type: "text", nullable: true })
    cashVoucherNumber: string | null;

    @Column({ type: "timestamptz", nullable: true })
    paidAt: Date | null;

    @Column({ type: "jsonb", default: [] })
    paymentProofs: PaymentRequestFile[];
}
