export enum MemberRole {
    CONTENT_CREATOR = "CONTENT_CREATOR",
    EDITOR = "EDITOR",
    GRAPHIC_DESIGNER = "GRAPHIC_DESIGNER",
    CAMERAMAN = "CAMERAMAN",
    PROJECT_MANAGER = "PROJECT_MANAGER",
    ACCOUNT = "ACCOUNT",
    SCRIPTER = "SCRIPTER",
    SOCIAL_MEDIA_MANAGER = "SOCIAL_MEDIA_MANAGER",
    SEO_SPECIALIST = "SEO_SPECIALIST"
}
