import test from "node:test";
import assert from "node:assert/strict";
import {
    PaymentRequests,
    PaymentRequestType,
    PaymentRequestApprovalStatus
} from "../entities/PaymentRequest.entity";
import { PaymentRequestService } from "./PaymentRequest.Service";

// Dựng service mà không cần kết nối DB: bỏ qua field initializer (AppDataSource.getRepository) và tiêm repo giả.
const buildService = (opts: { request?: Partial<PaymentRequests>; task?: any }) => {
    const service = Object.create(PaymentRequestService.prototype) as any;
    const saved: any[] = [];
    service.repo = {
        findOne: async () => opts.request,
        save: async (entity: any) => {
            saved.push(entity);
            return entity;
        }
    };
    service.taskRepo = { findOne: async () => opts.task };
    service.userRepo = { find: async () => [], findOne: async () => null };
    service.notificationService = { createNotification: async () => undefined };
    return { service, saved };
};

const vendorDraft = (): Partial<PaymentRequests> => ({
    id: "pr1",
    type: PaymentRequestType.PROJECT,
    approvalStatus: PaymentRequestApprovalStatus.DRAFT,
    projectId: "p1",
    taskId: "t1",
    vendorId: "v1",
    isAutoGenerated: true,
    requesterId: "pm1", // người phân công, KHÔNG phải assignee của task
    content: "Chi phí phát sinh - Vendor A",
    amount: 100,
    history: []
});

const vendorTask = (overrides: any = {}) => ({
    id: "t1",
    cost: 500,
    assigneeId: null,
    project: { id: "p1" },
    vendor: { id: "v1" },
    ...overrides
});

test("enum không còn VENDOR_EXPENSE (đã gộp vào PROJECT)", () => {
    assert.deepEqual(Object.values(PaymentRequestType).sort(), ["OTHER_WORK", "PROJECT"]);
});

test("create() từ chối type VENDOR_EXPENSE do client gửi", async () => {
    const { service } = buildService({});
    await assert.rejects(
        () => service.create({ type: "VENDOR_EXPENSE", content: "x", amount: 1, dueDate: "2026-10-01" }, "u1"),
        /Loại thanh toán không hợp lệ/
    );
});

test("update() cho phép sửa nháp vendor dù task không có assignee (người sửa là người phân công)", async () => {
    const { service, saved } = buildService({ request: vendorDraft(), task: vendorTask() });

    const result = await service.update("pr1", { amount: 300, content: "Đã kiểm tra" });

    assert.equal(saved.length, 1);
    assert.equal(result.amount, 300);
    assert.equal(result.content, "Đã kiểm tra");
    assert.equal(result.costPrice, 500); // lấy lại từ task.cost
});

test("update() khoá loại / dự án / công việc của yêu cầu vendor", async () => {
    const { service } = buildService({ request: vendorDraft(), task: vendorTask() });

    const result = await service.update("pr1", {
        type: PaymentRequestType.OTHER_WORK,
        projectId: "p2",
        taskId: "t2",
        amount: 250
    });

    assert.equal(result.type, PaymentRequestType.PROJECT);
    assert.equal(result.projectId, "p1");
    assert.equal(result.taskId, "t1");
    assert.equal(result.amount, 250);
});

test("update() từ chối khi task đã giao cho vendor khác", async () => {
    const { service } = buildService({
        request: vendorDraft(),
        task: vendorTask({ vendor: { id: "v2" } })
    });
    await assert.rejects(() => service.update("pr1", { amount: 1 }), /không còn được giao cho vendor này/);
});

test("update() PROJECT nội bộ vẫn yêu cầu task được giao cho chính người tạo", async () => {
    const internal = (): Partial<PaymentRequests> => ({
        ...vendorDraft(),
        vendorId: null,
        isAutoGenerated: false,
        requesterId: "u1"
    });

    const notMine = buildService({
        request: internal(),
        task: vendorTask({ vendor: null, assigneeId: "someone-else" })
    });
    await assert.rejects(() => notMine.service.update("pr1", { amount: 1 }), /không được giao cho bạn/);

    const mine = buildService({
        request: internal(),
        task: vendorTask({ vendor: null, assigneeId: "u1", cost: 0 })
    });
    const result = await mine.service.update("pr1", { amount: 7 });
    assert.equal(result.amount, 7);
});

test("createVendorExpense() tạo yêu cầu loại PROJECT, có vendorId, tự sinh, ở trạng thái DRAFT", async () => {
    const { service } = buildService({});
    let created: any;
    const manager = {
        getRepository: () => ({
            create: (data: any) => Object.assign(new PaymentRequests(), data),
            save: async (entity: any) => {
                created = entity;
                return entity;
            },
            findOne: async () => null
        })
    };

    await service.createVendorExpense(
        {
            projectId: "p1",
            taskId: "t1",
            vendorId: "v1",
            vendorName: "Vendor A",
            taskName: "Dựng video",
            amount: 500,
            dueDate: new Date("2026-10-01"),
            requesterId: "pm1"
        },
        manager as any
    );

    assert.equal(created.type, PaymentRequestType.PROJECT);
    assert.equal(created.vendorId, "v1");
    assert.equal(created.isAutoGenerated, true);
    assert.equal(created.approvalStatus, PaymentRequestApprovalStatus.DRAFT);
});
